In [116]:
import pandas as pd
import numpy as np
import pickle

In [117]:
# Load Training data
df = pd.read_csv('data/clean/dog_disease_train.csv', encoding='cp949')

df.head()

과호흡  급사  기침  염증  구토  탈모  무기력  발열  녹내장  거리감각불능  난청  요실금  설사  식욕부진  체중감소  \
0    0   0   0   0   1   0    1   0    0       1   0    0   0     0     0   
1    0   0   0   0   1   0    1   0    0       0   0    0   0     0     0   
2    0   0   0   0   0   0    1   0    0       1   0    0   0     0     0   
3    0   0   0   0   1   0    0   0    0       1   0    0   0     0     0   
4    0   0   0   0   1   0    1   0    0       1   0    0   0     0     0   

           질병명  
0  마카다미아너트 중독증  
1  마카다미아너트 중독증  
2  마카다미아너트 중독증  
3  마카다미아너트 중독증  
4  마카다미아너트 중독증

In [118]:
X = df.iloc[:, :-1]
y = df['질병명']

In [119]:
# Train, Test split
from sklearn.model_selection import train_test_split
from sklearn.externals import joblib 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=20)

In [120]:
# Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier()
# print(rf_clf)
# file_name = 'model4.sav'
# joblib.dump(rf_clf, file_name)
# loaded_model4 = pickle.load(open("model4.sav", "rb"))
# print(loaded_model4)


In [121]:
rf_clf.fit(X_train, y_train)
print(rf_clf)
print("Accuracy on split test: ", rf_clf.score(X_test,y_test))

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
Accuracy on split test:  1.0


In [136]:
#file_name = 'model2.sav'
#joblib.dump(rf_clf, file_name)

loaded_model = pickle.load(open("model.sav", "rb"))
# loaded_model2 = pickle.load(open("test.pkl", "rb"))
print(loaded_model)
print("------------")
# print(loaded_model2)
# file_name = 'model3.sav'
# joblib.dump(rf_clf, file_name)
# loaded_model3 = pickle.load(open("model3.sav", "rb"))
# print(loaded_model3)

# clf_load = joblib.dump(rf_clf, "test.pkl")
# from joblib import dump, load
# pickle.dumps(rf_clf, "test.joblib")

# print("model: ", loaded_model)
# print()
# print("rf_clf: ", s)

# from sklearn.externals import joblib
# file_name = 'model6.pkl'
# obj = rf_clf
# s = pickle.dumps(rf_clf)

# joblib.dump(s,"test.pkl")
# with open("model7.pkl",'wb') as fid:
#     pickle.dump(rf_clf, fid)

loaded_model7 = pickle.load(open("model7.pkl", "rb"))
print(loaded_model7)

RandomForestClassifier(bootstrap=True, ccp_alpha=None, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
                       oob_score=False, random_state=None, verbose=0,
                       warm_start=False)
------------
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                    

In [82]:
# Load real test data
df_test = pd.read_csv('data/clean/dog_disease_test.csv', encoding='cp949')

In [83]:
X_acutal_test = df_test.iloc[:, :-1]
y_actual_test = df_test['질병명']

In [84]:
print("Accuracy on acutal test: ", rf_clf.score(X_acutal_test, y_actual_test))

Accuracy on acutal test:  1.0


In [85]:
symptoms_dict = {}

for index, symptom in enumerate(X):
    symptoms_dict[symptom] = index

In [86]:
symptoms_dict

{'과호흡': 0,
 '급사': 1,
 '기침': 2,
 '염증': 3,
 '구토': 4,
 '탈모': 5,
 '무기력': 6,
 '발열': 7,
 '녹내장': 8,
 '거리감각불능': 9,
 '난청': 10,
 '요실금': 11,
 '설사': 12,
 '식욕부진': 13,
 '체중감소': 14}

In [87]:
input_vector = np.zeros(len(symptoms_dict))
print(input_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [88]:
input_vector[[symptoms_dict['발열'], symptoms_dict['거리감각불능'], symptoms_dict['식욕부진']]] = 1
print(input_vector)

[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.]


In [89]:
rf_clf.predict_proba([input_vector])

array([[0.  , 0.37, 0.63]])

In [90]:
rf_clf.predict([input_vector])

array(['코로나 바이러스 감염증'], dtype=object)